language: generic

install:
  - pushd $HOME
  - git clone https://github.com/samdoshi/avr32-toolchain-linux.git samdoshi/avr32-toolchain-linux
  - cd samdoshi/avr32-toolchain-linux
  - tar xvfz avr32-gnu-toolchain-3.4.3.820-linux.any.x86_64.tar.gz
  - mv avr32-gnu-toolchain-linux_x86_64 $HOME/avr32-tools
  - unzip avr32-headers-6.2.0.742.zip -d $HOME/avr32-tools/avr32/include
  - popd

before_script:
  - pushd $HOME
  - git clone https://github.com/$REPO.git $REPO
  - popd

script:
  - rm -rf $HOME/$REPO/$LIBAVR32_DIR
  - cp -r . $HOME/$REPO/$LIBAVR32_DIR
  - cd $HOME/$REPO/$SRC_DIR
  - PATH="$HOME/avr32-tools/bin:$PATH" make

matrix:
  include:
    - env:
        - REPO=monome/ansible
        - SRC_DIR=src
        - LIBAVR32_DIR=libavr32
    - env:
        - REPO=monome/teletype
        - SRC_DIR=module
        - LIBAVR32_DIR=libavr32

